### PR TITLE
Add updated architectural diagram via upload

### PR DESCRIPTION
**Pull request by tan-ro**

### CODE REVIEW

**Comment by tarka** [comment]
Clipped text ...

**Comment by tarka** [comment]
Separate from this update, the relationship between e.g the PV/PVCs and EFS/shared-FS haven't been shown, but I suppose that's not really important at this point?

**Comment by tan-ro** [comment]
Fixed clipped text

**Review by tarka — APPROVED** [review]

**Comment by nanux** [comment]
Thank you @tan-ro. I wanted to make a comment that the new diagram doesn't have an alpha channel and the background is not transparent but I've checked the current diagram with dark theme (I am using white by default).

Screen Shot 2021-07-23 at 10 37 07 am
Screen Shot 2021-07-23 at 10 37 15 am

I believe having a white background is definitely a better option.

**Comment by nanux** [comment]
Would it be possible to also add the updated xml source file? https://github.com/atlassian-labs/data-center-helm-charts/blob/master/docs/images/k8s%20overview.xml

**Comment by tan-ro** [comment]
Uploaded k8s_overview.xml

**Review by nanux — APPROVED** [review]

**Review by errcode1202 — APPROVED** [review]

**Pull request merged**
