### PR TITLE
DCKUBE-345: Enable clustering by default for all products

### PR DESCRIPTION
**Pull request by nanux**
* Switching clustering enabled by default
* The changes that will be applied to the default product manifests are visible in file with the expected output for each product

### CODE REVIEW

**Review by tarka — APPROVED** [review]

**Comment by apawelczyk-atlassian** [comment]
[ClusteringTest](https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/test/java/test/ClusteringTest.java) doesn't make much sense now. Maybe we should test whether clustering can be *disabled* instead?

**Review by apawelczyk-atlassian — APPROVED** [review]
[ClusteringTest](https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/test/java/test/ClusteringTest.java) doesn't make much sense now. Maybe we should test whether clustering can be *disabled* instead?

**Review by nghazali — APPROVED** [review]

**Review by errcode1202 — APPROVED** [review]

**Comment by nanux** [comment]
I am closing the PR as we are not going to tackle it now to enable users to create an installation with default values.

**Comment by nanux** [comment]
I am closing the PR as we are not going to tackle it now to enable users to create an installation with default values.

**Pull request closed without merging**
